### PR TITLE
Release Prep to Next Version of CDK Observability Accelerator

### PR DESCRIPTION
**Pull request by elamaran11**
*Issue #, if available:*

*Description of changes:*

Release Prep to Next Version of CDK Observability Accelerator
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by shapirov103 — APPROVED** [review]
LGTM
Please note that after blueprints update you will have to increment the version of blueprints and CDK.

**Comment by elamaran11** [comment]
Ignoring the E2E error.

**Pull request merged**
