### PR TITLE
Feature/issue 114 monitor adot collector

### PR DESCRIPTION
**Pull request by hmuthusamy**
*Issue #, if available:*
https://github.com/aws-observability/cdk-aws-observability-accelerator/issues/114
*Description of changes:*
A Pattern to monitor ADOT Collector health and add ADOT dashboard optionally using cdk.json configurations.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by elamaran11 — COMMENTED** [review]
@hmuthusamy Changes look good, Could you please run the changes with Fargate pattern alone and let us know if it works fine. I will kick e2e.

**Comment by hmuthusamy** [comment]
@elamaran11 Added snapshots for Fargate working scenario
Screenshot 2023-11-17 at 4 43 11 PM
Screenshot 2023-11-17 at 4 39 04 PM
Screenshot 2023-11-17 at 4 37 22 PM

**Review by elamaran11 — APPROVED** [review]
LGTM. Nice work @hmuthusamy Merging this.

**Pull request merged**
