### PR TITLE
Fixing AMP Endpoint Issue

### PR DESCRIPTION
**Pull request by elamaran11**
*Issue #, if available:*

*Description of changes:*
Fixing AMP Endpoint Issue

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by iamprakkie — APPROVED** [review]
LGTM

**Comment by elamaran11** [comment]
Delete Issue in e2e. Merging the PR.

**Pull request merged**
